package com.fagarester.translator

object LanguageData {
    private val languages = listOf(
        "af-ZA" to "Afrikaans (South Africa)",
        "am-ET" to "አማርኛ (Amharic / Ethiopia)",
        "ar-AE" to "العربية (Arabic / UAE)",
        "ar-BH" to "العربية (Arabic / Bahrain)",
        "ar-DZ" to "العربية (Arabic / Algeria)",
        "ar-EG" to "العربية (Arabic / Egypt)",
        "ar-IQ" to "العربية (Arabic / Iraq)",
        "ar-JO" to "العربية (Arabic / Jordan)",
        "ar-KW" to "العربية (Arabic / Kuwait)",
        "ar-LB" to "العربية (Arabic / Lebanon)",
        "ar-MA" to "العربية (Arabic / Morocco)",
        "ar-OM" to "العربية (Arabic / Oman)",
        "ar-QA" to "العربية (Arabic / Qatar)",
        "ar-SA" to "العربية (Arabic / Saudi Arabia)",
        "ar-TN" to "العربية (Arabic / Tunisia)",
        "ar-YE" to "العربية (Arabic / Yemen)",
        "as-IN" to "অসমীয়া (Assamese / India)",
        "az-AZ" to "Azərbaycanca (Azerbaijani)",
        "be-BY" to "Беларуская (Belarusian)",
        "bg-BG" to "Български (Bulgarian)",
        "bn-BD" to "বাংলা (Bengali / Bangladesh)",
        "bn-IN" to "বাংলা (Bengali / India)",
        "bs-BA" to "Bosanski (Bosnian)",
        "ca-ES" to "Català (Catalan)",
        "ceb-PH" to "Cebuano (Philippines)",
        "cs-CZ" to "Čeština (Czech)",
        "cy-GB" to "Cymraeg (Welsh)",
        "da-DK" to "Dansk (Danish)",
        "de-AT" to "Deutsch (Austrian)",
        "de-CH" to "Deutsch (Swiss)",
        "de-DE" to "Deutsch (Germany)",
        "el-GR" to "Ελληνικά (Greek)",
        "en-AU" to "English (Australia)",
        "en-CA" to "English (Canada)",
        "en-GB" to "English (UK)",
        "en-GH" to "English (Ghana)",
        "en-IE" to "English (Ireland)",
        "en-IN" to "English (India)",
        "en-KE" to "English (Kenya)",
        "en-NG" to "English (Nigeria)",
        "en-NZ" to "English (New Zealand)",
        "en-PH" to "English (Philippines)",
        "en-TZ" to "English (Tanzania)",
        "en-US" to "English (US)",
        "en-ZA" to "English (South Africa)",
        "es-AR" to "Español (Argentina)",
        "es-BO" to "Español (Bolivia)",
        "es-CL" to "Español (Chile)",
        "es-CO" to "Español (Colombia)",
        "es-CR" to "Español (Costa Rica)",
        "es-DO" to "Español (Dominican Republic)",
        "es-EC" to "Español (Ecuador)",
        "es-ES" to "Español (España)",
        "es-GT" to "Español (Guatemala)",
        "es-HN" to "Español (Honduras)",
        "es-MX" to "Español (México)",
        "es-NI" to "Español (Nicaragua)",
        "es-PA" to "Español (Panamá)",
        "es-PE" to "Español (Perú)",
        "es-PR" to "Español (Puerto Rico)",
        "es-PY" to "Español (Paraguay)",
        "es-SV" to "Español (El Salvador)",
        "es-US" to "Español (Estados Unidos)",
        "es-UY" to "Español (Uruguay)",
        "es-VE" to "Español (Venezuela)",
        "et-EE" to "Eesti (Estonian)",
        "eu-ES" to "Euskara (Basque)",
        "fa-IR" to "فارسی (Persian)",
        "fi-FI" to "Suomi (Finnish)",
        "fil-PH" to "Filipino (Philippines)",
        "fr-BE" to "Français (Belgique)",
        "fr-CA" to "Français (Canada)",
        "fr-CH" to "Français (Suisse)",
        "fr-FR" to "Français (France)",
        "ga-IE" to "Gaeilge (Irish)",
        "gl-ES" to "Galego (Galician)",
        "gu-IN" to "ગુજરાતી (Gujarati / India)",
        "ha-NG" to "Hausa (Nigeria)",
        "he-IL" to "עברית (Hebrew)",
        "hi-IN" to "हिन्दी (Hindi)",
        "hr-HR" to "Hrvatski (Croatian)",
        "hu-HU" to "Magyar (Hungarian)",
        "hy-AM" to "Հայերեն (Armenian)",
        "id-ID" to "Bahasa Indonesia",
        "ig-NG" to "Igbo (Nigeria)",
        "is-IS" to "Íslenska (Icelandic)",
        "it-CH" to "Italiano (Svizzera)",
        "it-IT" to "Italiano (Italia)",
        "ja-JP" to "日本語 (Japanese)",
        "jv-ID" to "Javanese (Indonesia)",
        "ka-GE" to "ქართული (Georgian)",
        "kk-KZ" to "Қазақ тілі (Kazakh)",
        "km-KH" to "ខ្មែរ (Khmer / Cambodia)",
        "kn-IN" to "ಕನ್ನಡ (Kannada / India)",
        "ko-KR" to "한국어 (Korean)",
        "ky-KG" to "Кыргызча (Kyrgyz)",
        "lo-LA" to "ລາວ (Lao)",
        "lt-LT" to "Lietuvių (Lithuanian)",
        "lv-LV" to "Latviešu (Latvian)",
        "mk-MK" to "Македонски (Macedonian)",
        "ml-IN" to "മലയാളം (Malayalam / India)",
        "mn-MN" to "Монгол (Mongolian)",
        "mr-IN" to "मराठी (Marathi / India)",
        "ms-MY" to "Bahasa Melayu (Malaysia)",
        "mt-MT" to "Malti (Maltese)",
        "my-MM" to "မြန်မာ (Burmese)",
        "nb-NO" to "Norsk Bokmål (Norway)",
        "ne-NP" to "नेपाली (Nepali / Nepal)",
        "nl-BE" to "Nederlands (België)",
        "nl-NL" to "Nederlands (Nederland)",
        "nn-NO" to "Norsk Nynorsk (Norway)",
        "or-IN" to "ଓଡ଼ିଆ (Odia / India)",
        "pa-IN" to "ਪੰਜਾਬੀ (Punjabi / India)",
        "pl-PL" to "Polski (Polish)",
        "ps-AF" to "پښتو (Pashto / Afghanistan)",
        "pt-BR" to "Português (Brasil)",
        "pt-PT" to "Português (Portugal)",
        "ro-RO" to "Română (Romanian)",
        "ru-RU" to "Русский (Russian)",
        "rw-RW" to "Kinyarwanda (Rwanda)",
        "si-LK" to "සිංහල (Sinhala / Sri Lanka)",
        "sk-SK" to "Slovenčina (Slovak)",
        "sl-SI" to "Slovenščina (Slovenian)",
        "sn-ZW" to "shona (Zimbabwe)",
        "so-SO" to "Somali",
        "sq-AL" to "Shqip (Albanian)",
        "sr-RS" to "Српски (Serbian)",
        "su-ID" to "Sundanese (Indonesia)",
        "sv-SE" to "Svenska (Swedish)",
        "sw-KE" to "Kiswahili (Kenya)",
        "sw-TZ" to "Kiswahili (Tanzania)",
        "ta-IN" to "தமிழ் (Tamil / India)",
        "ta-LK" to "தமிழ் (Tamil / Sri Lanka)",
        "te-IN" to "తెలుగు (Telugu / India)",
        "tg-TJ" to "Тоҷикӣ (Tajik)",
        "th-TH" to "ไทย (Thai)",
        "tl-PH" to "Tagalog (Filipino)",
        "tr-TR" to "Türkçe (Turkish)",
        "uk-UA" to "Українська (Ukrainian)",
        "ur-IN" to "اردو (Urdu / India)",
        "ur-PK" to "اردو (Urdu / Pakistan)",
        "uz-UZ" to "Oʻzbekcha (Uzbek)",
        "vi-VN" to "Tiếng Việt (Vietnamese)",
        "xh-ZA" to "isiXhosa (South Africa)",
        "yo-NG" to "Yorùbá (Nigeria)",
        "zh-CN" to "Chinese (Simplified / China)",
        "zh-HK" to "Chinese (Traditional / Hong Kong)",
        "zh-TW" to "Chinese (Traditional / Taiwan)",
        "zu-ZA" to "isiZulu (South Africa)"
    )

    fun getAvailableLanguages(): List<Pair<String, String>> = languages
}